# Generated by Django 4.2.11 on 2024-06-06 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "birth_year",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1900),
                            django.core.validators.MaxValueValidator(2024),
                        ]
                    ),
                ),
                ("start_date", models.DateField()),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("permanent", "Permanent"),
                            ("fixed-term", "Fixed-term"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "contract_duration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("hr", "Human Resources"),
                            ("it", "Information Technology"),
                            ("sales", "Sales"),
                            ("finance", "Finance"),
                            ("marketing", "Marketing"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "annual_leave_days",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("free_days", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "paid_leave_days",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
            ],
        ),
    ]
