# Generated by Django 4.2.11 on 2024-06-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0003_alter_employee_contract_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="photo",
            field=models.ImageField(
                default="employee_photos/default.jpg", upload_to="employee_photos/"
            ),
            preserve_default=False,
        ),
    ]
