# Generated by Django 4.2.11 on 2024-06-08 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0004_employee_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="photo",
        ),
    ]
