# Generated by Django 4.2.11 on 2024-06-08 10:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employee", "0005_remove_employee_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="contract_duration",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="first_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]+$", "Only letters are allowed."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_name",
            field=models.CharField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Z]+$", "Only letters are allowed."
                    )
                ],
            ),
        ),
    ]
